name: hotel-group-bf-dev

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hotel_group_bf
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

# # spring.application.name=group-bf
#
# # Database Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/hotel_group_bf
# spring.datasource.username=root
# spring.datasource.password=1234
#
# # Hibernate Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.jpa.show-sql=true
